version: "3"

services:
  vault:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "root"
    cap_add:
      - IPC_LOCK
  consul:
    image: consul:latest
    ports:
      - "8500:8500" 
  loki:
    image: grafana/loki:2.7.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  promtail:
    image: grafana/promtail:2.7.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - "3000:3000"
  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./dockerfs/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
  coffeepot:
    build: ./dockerfs/coffeepot
    ports:
      - "8000:8000"
      - "8001:8001"
