- name: debug
  hosts: all
  tasks:
    - name: show facts
      debug:
        var: ansible_facts
    - name: service template
      become: true
      ansible.builtin.template:
        src: templates/coffeepot.service.j2
        dest: /etc/systemd/system/coffeepot.service
